# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/user/proto/user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'services/user/proto/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eservices/user/proto/user.proto\x12\x04user\"-\n\x07Request\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x19\n\x06Result\x12\x0f\n\x07\x63orrect\x18\x01 \x01(\x08\x32\x30\n\x04User\x12(\n\tCheckUser\x12\r.user.Request\x1a\x0c.user.ResultBQZOgithub.com/delimitrou/DeathStarBench/tree/master/hotelReservation/services/userb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.user.proto.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZOgithub.com/delimitrou/DeathStarBench/tree/master/hotelReservation/services/user'
  _globals['_REQUEST']._serialized_start=40
  _globals['_REQUEST']._serialized_end=85
  _globals['_RESULT']._serialized_start=87
  _globals['_RESULT']._serialized_end=112
  _globals['_USER']._serialized_start=114
  _globals['_USER']._serialized_end=162
# @@protoc_insertion_point(module_scope)
