# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/recommendation/proto/recommendation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'services/recommendation/proto/recommendation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2services/recommendation/proto/recommendation.proto\x12\x0erecommendation\"4\n\x07Request\x12\x0f\n\x07require\x18\x01 \x01(\t\x12\x0b\n\x03lat\x18\x02 \x01(\x01\x12\x0b\n\x03lon\x18\x03 \x01(\x01\"\x1a\n\x06Result\x12\x10\n\x08HotelIds\x18\x01 \x03(\t2W\n\x0eRecommendation\x12\x45\n\x12GetRecommendations\x12\x17.recommendation.Request\x1a\x16.recommendation.ResultB[ZYgithub.com/delimitrou/DeathStarBench/tree/master/hotelReservation/services/recommendationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.recommendation.proto.recommendation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZYgithub.com/delimitrou/DeathStarBench/tree/master/hotelReservation/services/recommendation'
  _globals['_REQUEST']._serialized_start=70
  _globals['_REQUEST']._serialized_end=122
  _globals['_RESULT']._serialized_start=124
  _globals['_RESULT']._serialized_end=150
  _globals['_RECOMMENDATION']._serialized_start=152
  _globals['_RECOMMENDATION']._serialized_end=239
# @@protoc_insertion_point(module_scope)
